
# Syntax highlighting
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           /:title

# Setup
timezone:            Europe/Warsaw # eg. 
locale:              en_us # eg. en_us
name:				         '100 Words About'
title:               '100 Words About'
tagline:             '100 слiв про, 100 słów o, 100 слов о...'
description:         'I am pleased to see you on my site. I prefer short stories, which can be expressed in a 100 words. I use 4 languages from my environment, the text is not translation,although you can catch the main thought anyway ;)'
url:                 'http://100wordsabout.me'
rss:                 'feed.xml'
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              mriyaa # get it on https://disqus.com/admin/

author:
  name:           	 Maria
  url:            	 'http://100wordsabout.me'
  facebook:          maria.prkh
  linkedin:          username
  instagram:         maria_prkh

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
